version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.json
checks:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
  identical-code:
    enabled: true
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
ratings:
  paths:
    - "src/**/*.js"
exclude_paths:
  - "build"
  - "config"
  - "coverage"
  - "node_modules"
  - "public"
  - "scripts"
  - "src/**/*.dev.{js,jsx,mjs}"
  - "spec"
  - "task"
