sudo: required
language: node_js
node_js:
- '9'
before_install:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
  - npm install
  - npm install -g jest-cli
script:
  - npm run build
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
