language: node_js
node_js:
- '9'
env:
  global:
    - CC_TEST_REPORTER_ID=38e7c4a1b2546f768f1b349e3fabb002015c4bb54b3ad40df6f0f860412dc12b
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
before_script:
- npm install
- npm install -g jest-cli
script:
- npm run build
- npm run coverage
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
